githubConfigSecret:
    github_token: ENC[AES256_GCM,data:iX8p34cqwlVhktFkTunX49zxO3kwO11QcvQnrhDsWd40zzQIV3dAmw==,iv:d9Ib79kEgducTc9sGxFuHUtO0SonxkNqYR1LB3X9EgE=,tag:TQNDjgVA5dNGc8gCSK3CeQ==,type:str]
sops:
    age:
        - recipient: age1k3lurupezx34ngmqdzlwlw4k7pavq3fe36wtyz2x2ka774mq3fts60s386
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTGVlTjBwaytrVWhZQ0hZ
            Rk5qZUZhdmYwNExGTmVSTHlaU0Z3TFVsZTFnCjdGbTJCSHllcTgzUzY5T2d4V0RD
            NVRTNFMxMjM4d2Z3bDdWR2lnOHhVRGMKLS0tIGJrWW1ocCtFSFBZUndjU3N4MXor
            S2VzOHVSdktyWkVNV1BNWTVXMmpiR2sKQTZcxFMefqiHFizDCQXNotJ1X9l2sNQV
            9fHwnRBGVLQB6wEYSGaDwbCN6RTm0A4hCVPpsTTLl2hsmvDq1hxTxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T19:52:25Z"
    mac: ENC[AES256_GCM,data:n0ZDIC2iFknZSDiOJldkZG9F/9YoXVmnaWrgvtAamYYYoNZGyMjs4wNdmikG1FFvvjpIudoJpA1EhUw0otuM9Soy1GD11zkWNyJM0lslG5AWoeVrpqsZuQAjHjWcoUh7j0AFHBbpMmUjw7DeUcUS+UaZM8x8CietIRerORgM990=,iv:qzTl7btt8i4ecU7sew5T+r9bFUV7wqXdT2Cf9wrbgMs=,tag:K6bqMZ5Y3jhkFCJ2ruqmXw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
